### ISSUE TITLE
ModuleNotFoundError in examples

### ISSUE THREAD

**Issue by nicw** [MyHomeAutomations/python-actioncable-zwei#1]
Following the README verbatim, and pasting in the examples, I'm getting an error finding the modules. I'm new to Python, but something seems off.

`Traceback (most recent call last):
  File "./actioncable.py", line 1, in <module>
    from actioncable.subscription import Subscription
  File "/Users/nic/programming/test_python/actioncable.py", line 1, in <module>
    from actioncable.subscription import Subscription
ModuleNotFoundError: No module named 'actioncable.subscription'; 'actioncable' is not a package`

Also: Thanks for writing this! I lost the entire morning thinking that ActionCable was so great, only to realize that as always, it only works well inside a Rails world where all the parameters are abstracted away. :(

**Comment by nicw** [comment]
Nevermind, long day. Now I have it "running" but nothing happens, or connect. Will continue to test.
